/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.mysql.jdbc.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author ROG G531
 */
public class frameAplikasiObjekWisata extends javax.swing.JFrame {
    String[] Judulnya ={"ID Wisata","Nama Wisata","Kategori","Alamat","Biaya","Stock"};
    int[] LebarKolomOW ={120,270,200,100,200,100};
    String SQL = "SELECT*FROM wisata";
    
    String[] Namanya ={"ID Pengunjung","Nama Pengunjung","Tempat Lahir","Jenis Kelamin","Status","Alamat","Telepon"};
    int[] LebarKolomPengunjung ={120,270,200,100,100,200,100};
    String SQL1 = "SELECT*FROM pengunjung";
    
    String[] Transaksi ={"ID Transaksi","Nama Wisata","Harga Wisata","Waktu Transaksi","Jumlah Tiket","Total Biaya"};
    int[] LebarKolomTransaksi ={120,270,200,100,100,100};
    String SQL2 = "SELECT*FROM transaksi";
    /**
     * Creates new form frameAplikasiObjekWisata
     */
    public frameAplikasiObjekWisata() {
        initComponents();
        this.setLocationRelativeTo(null);
        new configDBOW().setJudulKolom(tabelPariswisata, Judulnya);
        new configDBOW().setTampilTabel(tabelPariswisata, Judulnya, SQL);
        new configDBOW().setLebarJudulKolom(tabelPariswisata, LebarKolomOW);
        this.setLocationRelativeTo(null);
        new configDBOW().setJudulKolom(tabelPengunjung, Namanya);
        new configDBOW().setTampilTabel(tabelPengunjung,Namanya, SQL1 );
        new configDBOW().setLebarJudulKolom(tabelPengunjung, LebarKolomPengunjung);
         this.setLocationRelativeTo(null);
        new configDBOW().setJudulKolom(tabelTransaksi, Transaksi);
        new configDBOW().setTampilTabel(tabelTransaksi,Transaksi, SQL2 );
        new configDBOW().setLebarJudulKolom(tabelPengunjung, LebarKolomTransaksi);
       
        
    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        panelBody = new javax.swing.JPanel();
        panelBeranda = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        panelPariswisata = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textIDWisata = new javax.swing.JTextField();
        textNamaWisata = new javax.swing.JTextField();
        textKategori = new javax.swing.JTextField();
        textAlamat = new javax.swing.JTextField();
        textBiaya = new javax.swing.JTextField();
        textStock = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textPencarianWisata = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPanel1 = new javax.swing.JScrollPane();
        tabelPariswisata = new javax.swing.JTable();
        panelPengunjung = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        textIDPengunjung = new javax.swing.JTextField();
        textNamaLengkap = new javax.swing.JTextField();
        textTempatLahir = new javax.swing.JTextField();
        textAlamat1 = new javax.swing.JTextField();
        textTelepon = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        textPencarianPengunjung = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPengunjung = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cbJenisKelamin = new javax.swing.JComboBox<>();
        textStatus = new javax.swing.JTextField();
        panelTransaksi = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        textIDTransaksi = new javax.swing.JTextField();
        textNamaWisata1 = new javax.swing.JTextField();
        textHargaTiket = new javax.swing.JTextField();
        textJumlahBeli = new javax.swing.JTextField();
        textTotalBiaya = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        textPencarianTransaksi = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        dateTransaksi = new com.toedter.calendar.JDateChooser();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi BASTARI Wisata ");

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("APLIKASI BASTARI WISATA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Layanan Info tentang objek wisata yang beranda di kabupaten Tapin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 0, 204));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N
        jButton1.setText("Beranda");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/money-transfer.png"))); // NOI18N
        jButton2.setText("Transaksi");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/visitor.png"))); // NOI18N
        jButton3.setText("Pengunjung");
        jButton3.setToolTipText("");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lake.png"))); // NOI18N
        jButton4.setText("Pariswisata");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(153, 153, 153));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/log-out.png"))); // NOI18N
        jButton5.setText("LOG OUT");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBody.setBackground(new java.awt.Color(204, 51, 255));
        panelBody.setLayout(new java.awt.CardLayout());

        panelBeranda.setBackground(new java.awt.Color(204, 0, 204));
        panelBeranda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 17)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Aplikasi BASTARI WISATA adalah suatu pelayanan informasi dalam berbasis GUI Java");
        panelBeranda.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 39, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 17)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("menu panel. untuk memudahkan dalam memilih navigasi menu dalam satu frame dengan 4 panel ");
        panelBeranda.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 20));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 17)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("objek wisata yang berada di wiliyah Kabupaten Tapin, provinsi kalimantan selatan.\n\n");
        panelBeranda.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 17)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Aplikasi BASTARI Wisata ini sangat user friendly dengan menggunakan GUI Dynamic\n");
        panelBeranda.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 17)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("implementasi dari CRUD dan menggunakan Database Mysql yang menyediakan layanan tentang info");
        panelBeranda.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 73, -1, -1));

        panelBody.add(panelBeranda, "card2");

        panelPariswisata.setBackground(new java.awt.Color(204, 0, 204));
        panelPariswisata.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID Wisata");
        panelPariswisata.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 59, 108, -1));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama Wisata");
        panelPariswisata.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tempat Wisata");
        panelPariswisata.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kategori");
        panelPariswisata.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 108, -1));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Biaya");
        panelPariswisata.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 108, -1));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Stock Tiket");
        panelPariswisata.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 120, -1));
        panelPariswisata.add(textIDWisata, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 60, 165, -1));
        panelPariswisata.add(textNamaWisata, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 426, -1));
        panelPariswisata.add(textKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 426, -1));
        panelPariswisata.add(textAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 426, -1));
        panelPariswisata.add(textBiaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 430, -1));
        panelPariswisata.add(textStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 164, -1));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cari Data Wisata ");
        panelPariswisata.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 331, -1, -1));

        textPencarianWisata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPencarianWisataActionPerformed(evt);
            }
        });
        textPencarianWisata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textPencarianWisataKeyPressed(evt);
            }
        });
        panelPariswisata.add(textPencarianWisata, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 332, 673, -1));

        jButton6.setBackground(new java.awt.Color(153, 153, 153));
        jButton6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        jButton6.setText("Delete");
        jButton6.setToolTipText("");
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panelPariswisata.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 196, 159, 40));

        jButton7.setBackground(new java.awt.Color(153, 153, 153));
        jButton7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/diskette.png"))); // NOI18N
        jButton7.setText("Save");
        jButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panelPariswisata.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 64, 159, 40));

        jButton8.setBackground(new java.awt.Color(153, 153, 153));
        jButton8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        jButton8.setText("Edit");
        jButton8.setToolTipText("");
        jButton8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        panelPariswisata.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 129, 159, 40));

        jButton9.setBackground(new java.awt.Color(153, 153, 153));
        jButton9.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/printer.png"))); // NOI18N
        jButton9.setText("Print");
        jButton9.setToolTipText("");
        jButton9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        panelPariswisata.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 260, 159, 40));

        tabelPariswisata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPanel1.setViewportView(tabelPariswisata);

        panelPariswisata.add(jScrollPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 910, 170));

        panelBody.add(panelPariswisata, "card3");

        panelPengunjung.setBackground(new java.awt.Color(204, 0, 204));
        panelPengunjung.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID Pengunjung");
        panelPengunjung.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, -1));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nama Lengkap");
        panelPengunjung.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Jenis Kelamin");
        panelPengunjung.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 140, -1));

        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Alamat");
        panelPengunjung.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 108, -1));

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("telepon");
        panelPengunjung.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 108, -1));
        panelPengunjung.add(textIDPengunjung, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 165, -1));
        panelPengunjung.add(textNamaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 426, -1));
        panelPengunjung.add(textTempatLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 426, -1));
        panelPengunjung.add(textAlamat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 430, 20));
        panelPengunjung.add(textTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 164, -1));

        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Cari Data Pengunjung");
        panelPengunjung.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 331, -1, -1));

        textPencarianPengunjung.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textPencarianPengunjungKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textPencarianPengunjungKeyReleased(evt);
            }
        });
        panelPengunjung.add(textPencarianPengunjung, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 673, -1));

        jButton10.setBackground(new java.awt.Color(153, 153, 153));
        jButton10.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        jButton10.setText("Delete");
        jButton10.setToolTipText("");
        jButton10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        panelPengunjung.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 196, 159, 40));

        jButton11.setBackground(new java.awt.Color(153, 153, 153));
        jButton11.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/diskette.png"))); // NOI18N
        jButton11.setText("Save");
        jButton11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        panelPengunjung.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 64, 159, 40));

        jButton12.setBackground(new java.awt.Color(153, 153, 153));
        jButton12.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        jButton12.setText("Edit");
        jButton12.setToolTipText("");
        jButton12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        panelPengunjung.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 129, 159, 40));

        jButton13.setBackground(new java.awt.Color(153, 153, 153));
        jButton13.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/printer.png"))); // NOI18N
        jButton13.setText("Print");
        jButton13.setToolTipText("");
        jButton13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        panelPengunjung.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 260, 159, 40));

        tabelPengunjung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelPengunjung);

        panelPengunjung.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 910, 170));

        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("TTL");
        panelPengunjung.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Status");
        panelPengunjung.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 108, -1));

        cbJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan", " " }));
        cbJenisKelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenisKelaminActionPerformed(evt);
            }
        });
        panelPengunjung.add(cbJenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 170, -1));
        panelPengunjung.add(textStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 164, -1));

        panelBody.add(panelPengunjung, "card4");

        panelTransaksi.setBackground(new java.awt.Color(204, 0, 204));
        panelTransaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("ID Transaksi");
        panelTransaksi.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 59, 130, -1));

        jLabel24.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Harga Tiket");
        panelTransaksi.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel25.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Nama Wisata");
        panelTransaksi.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel26.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Waktu Transaksi");
        panelTransaksi.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 170, -1));

        jLabel27.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Jumlah Beli");
        panelTransaksi.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 140, -1));

        jLabel28.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Total Biaya");
        panelTransaksi.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 130, -1));
        panelTransaksi.add(textIDTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 60, 165, -1));

        textNamaWisata1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNamaWisata1ActionPerformed(evt);
            }
        });
        panelTransaksi.add(textNamaWisata1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 426, -1));
        panelTransaksi.add(textHargaTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 426, -1));
        panelTransaksi.add(textJumlahBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 164, -1));
        panelTransaksi.add(textTotalBiaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 164, -1));

        jLabel29.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Cari Data Transaksi");
        panelTransaksi.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 331, -1, -1));
        panelTransaksi.add(textPencarianTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 673, -1));

        jButton14.setBackground(new java.awt.Color(153, 153, 153));
        jButton14.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        jButton14.setText("Delete");
        jButton14.setToolTipText("");
        jButton14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        panelTransaksi.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 196, 159, 40));

        jButton15.setBackground(new java.awt.Color(153, 153, 153));
        jButton15.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/diskette.png"))); // NOI18N
        jButton15.setText("Save");
        jButton15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        panelTransaksi.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 64, 159, 40));

        jButton16.setBackground(new java.awt.Color(153, 153, 153));
        jButton16.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        jButton16.setText("Edit");
        jButton16.setToolTipText("");
        jButton16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        panelTransaksi.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 129, 159, 40));

        jButton17.setBackground(new java.awt.Color(153, 153, 153));
        jButton17.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/printer.png"))); // NOI18N
        jButton17.setText("Print");
        jButton17.setToolTipText("");
        jButton17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        panelTransaksi.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 260, 159, 40));

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelTransaksi);

        panelTransaksi.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 910, 180));
        panelTransaksi.add(dateTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 160, -1));

        panelBody.add(panelTransaksi, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // remove panel
        panelBody.removeAll();
        panelBody.repaint();
        panelBody.revalidate();
        
        // add panel
        panelBody.add(panelBeranda);
        panelBody.repaint();
        panelBody.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        panelBody.removeAll();
        panelBody.repaint();
        panelBody.revalidate();
        
        // add panel
        panelBody.add(panelPariswisata);
        panelBody.repaint();
        panelBody.revalidate();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        panelBody.removeAll();
        panelBody.repaint();
        panelBody.revalidate();
        
        // add panel
        panelBody.add(panelPengunjung);
        panelBody.repaint();
        panelBody.revalidate();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbJenisKelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisKelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJenisKelaminActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        panelBody.removeAll();
        panelBody.repaint();
        panelBody.revalidate();
        
        // add panel
        panelBody.add(panelTransaksi);
        panelBody.repaint();
        panelBody.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         if (textIDWisata.getText().equals("")){
            JOptionPane.showMessageDialog(null,"ID Wisata Belum diisi");
            textIDWisata.requestFocus();
        }else if (textNamaWisata.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Nama Wisata Belum diisi");
            textNamaWisata.requestFocus();
        }else if(textKategori.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Kategori Wisata Belum diisi");
            textKategori.requestFocus();  
        }else if (textAlamat.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Alamat Wisata Belum diisi");
             textAlamat.requestFocus();
        }else if (textBiaya.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Biaya Wisata Belum diisi");
            textBiaya.requestFocus();
        }else if (textStock.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Stok Ticket Wisata Belum diisi");
            textStock.requestFocus();
        } else if (new configDBOW().getDuplikasiKey("wisata","id_wisata",textIDWisata.getText())){
            JOptionPane.showMessageDialog(null,"ID Wisata sudah terdaftar");
        }else{
           // area koding simpan 
           
           String[] F = {"id_wisata","nama_wisata","kategori","alamat","biaya","stock"};
           String[] isinya ={textIDWisata.getText(),textNamaWisata.getText(),textKategori.getText(),textAlamat.getText(),textBiaya.getText(),textStock.getText()};
           new configDBOW().SimpanDinamis("wisata", F, isinya);
           
        new configDBOW().setJudulKolom(tabelPariswisata, Judulnya);
        new configDBOW().setTampilTabel(tabelPariswisata, Judulnya, SQL);
        new configDBOW().setLebarJudulKolom(tabelPariswisata, LebarKolomOW);
        
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String tKode = textIDWisata.getText();
        String tJudul = textNamaWisata.getText();
        String tGenre = textKategori.getText();
        String tTahun = textAlamat.getText();
        String tAsal = textBiaya.getText();
        String tStok = textStock.getText();
        
        String fieldnya[] = {"nama_wisata","kategori","alamat","biaya","stock"};
        String isinya[] = {tJudul,tGenre,tTahun,tAsal,tStok};
        
      
        new configDBOW().UbahDinamis("wisata", "id_wisata", tKode, fieldnya, isinya);
        
         new configDBOW().setJudulKolom(tabelPariswisata, Judulnya);
        new configDBOW().setTampilTabel(tabelPariswisata, Judulnya, SQL);
        new configDBOW().setLebarJudulKolom(tabelPariswisata, LebarKolomOW);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new configDBOW().HapusDinamis("wisata", "id_wisata", textIDWisata.getText());
       
        new configDBOW().setJudulKolom(tabelPariswisata, Judulnya);
        new configDBOW().setTampilTabel(tabelPariswisata, Judulnya, SQL);
        new configDBOW().setLebarJudulKolom(tabelPariswisata, LebarKolomOW);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void textPencarianWisataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPencarianWisataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPencarianWisataActionPerformed

    private void textPencarianWisataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPencarianWisataKeyPressed
        // TODO add your handling code here:
        String SQLCari ="SELECT*FROM wisata WHERE id_wisata LIKE '%"+textPencarianWisata.getText()+"%' OR nama_wisata LIKE '%"+textPencarianWisata.getText()+"%' ";
      new configDBOW().setJudulKolom(tabelPariswisata, Judulnya);
      new configDBOW().cariData(tabelPariswisata, Judulnya, SQLCari);
      new configDBOW().setLebarJudulKolom(tabelPariswisata, LebarKolomOW);
    }//GEN-LAST:event_textPencarianWisataKeyPressed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        new configDBOW().tampilLaporan("src/laporan/lapWisata.jrxml","SELECT*FROM wisata");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        try {
        if (textIDPengunjung.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"ID Pengunjung belum diisi");
            textIDPengunjung.requestFocus();
        }else
        if(textNamaLengkap.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Nama Lengkap Pengunjung belum diisi");
            textNamaLengkap.requestFocus();
        }else
        if(textTempatLahir.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Tempat Lahir Pengunjung belum diisi");
            textTempatLahir.requestFocus();
        }else
        if(cbJenisKelamin.getSelectedItem()==".: Pilih Data :."){
            JOptionPane.showMessageDialog(null,"Jenis Kelamin Anggota belum diisi");
            cbJenisKelamin.requestFocus();
        } else
        if(textStatus.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Status Pengunjung belum diisi");
            textStatus.requestFocus();
        }else
        if(textAlamat1.getText().isEmpty()){
           JOptionPane.showMessageDialog(null,"ALamat Pengunjung belum diisi");
            textAlamat1.requestFocus();
        }else
        if(textTelepon.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Nomor Telp Anggota belum diisi");
            textTelepon.requestFocus();
        } else
        if (new configDBOW().getDuplikasiKey("pengunjung","id_pengunjung",textIDPengunjung.getText())==true){
            JOptionPane.showMessageDialog(null,"ID Pengunjung sudah terdaftar");
            java.sql.Statement st = new configDBOW().getKoneksi.createStatement();
            java.sql.ResultSet rs = st.executeQuery("SELECT*FROM pengunjung WHERE id_pengunjung='"+textIDPengunjung.getText()+"'");
        if(rs.next()){
             textNamaLengkap.setText(rs.getString("nama_pengunjung"));
             textTempatLahir.setText(rs.getString("tempat_lahir"));
             cbJenisKelamin.setSelectedItem(String.valueOf(rs.getString("jenis_kelamin")));
             textStatus.setText(String.valueOf(rs.getString("status")));
             textAlamat1.setText(rs.getString("alamat"));
             textTelepon.setText(rs.getString("telepon"));
}
}
         else{
            String[] F = {"id_pengunjung","nama_pengunjung","tempat_lahir","jenis_kelamin","status","alamat","telepon"};
           String[] isinya ={textIDPengunjung.getText(),textNamaLengkap.getText(),textTempatLahir.getText(),String.valueOf(cbJenisKelamin.getSelectedItem()),textStatus.getText(),textAlamat1.getText(),textTelepon.getText()};
           new configDBOW().SimpanDinamis("pengunjung", F, isinya);

            new configDBOW().setTampilTabel(tabelPengunjung,Namanya, SQL1);
            new configDBOW().setLebarJudulKolom(tabelPengunjung, LebarKolomPengunjung);
            

          
}
        } catch (Exception e) {
            System.out.print(e.toString());

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        try{
            
        
         if (
            (textIDPengunjung.getText().isEmpty()) && (textNamaLengkap.getText().isEmpty()) && (textTempatLahir.getText().isEmpty()) &&  (textAlamat1.getText().isEmpty()) &&  (textTelepon.getText().isEmpty()) && (cbJenisKelamin.getSelectedItem()==".: Pilih Data :.") && (textStatus.getText().isEmpty())){ 
            JOptionPane.showMessageDialog(null,"Silahkan pilih data sebelum proses ubah");
            tabelPengunjung.requestFocus();
         } else{
            String[] F = {"nama_pengunjung","tempat_lahir","Jenis_kelamin","status","alamat","telepon"};
            String[] isinya ={textNamaLengkap.getText(),textTempatLahir.getText(),String.valueOf(cbJenisKelamin.getSelectedItem()),textStatus.getText(),textAlamat1.getText(),textTelepon.getText()};
            new configDBOW().UbahDinamis("Pengunjung", "id_pengunjung", textIDPengunjung.getText(), F, isinya);
            new configDBOW().setTampilTabel(tabelPengunjung,Namanya, SQL1);
            new configDBOW().setLebarJudulKolom(tabelPengunjung, LebarKolomPengunjung);
         }
        } catch (Exception e) {
        System.out.print(e.toString());
                
    }   
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        
        if (
            (textIDPengunjung.getText().isEmpty()) &&(textNamaLengkap.getText().isEmpty())&&(textTempatLahir.getText().isEmpty())&& (textAlamat1.getText().isEmpty()) &&(textTelepon.getText().isEmpty())&&(cbJenisKelamin.getSelectedItem()==".:Pilih Data:.")&& (textStatus.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null,"Silahkan pilih data sebelum proses hapus ");
            tabelPengunjung.requestFocus();
       } else{
           
            new configDBOW().HapusDinamis("pengunjung", "id_pengunjung", textIDPengunjung.getText());
            new configDBOW().setTampilTabel(tabelPengunjung,Namanya, SQL1);
            new configDBOW().setLebarJudulKolom(tabelPengunjung, LebarKolomPengunjung);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void textPencarianPengunjungKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPencarianPengunjungKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_textPencarianPengunjungKeyReleased

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        new configDBOW().tampilLaporan("src/laporan/lapPengunjung.jrxml","SELECT*FROM pengunjung");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void textPencarianPengunjungKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPencarianPengunjungKeyPressed
        // TODO add your handling code here:
        String SQLCari1 ="SELECT*FROM pengunjung WHERE id_pengunjung LIKE '%"+textPencarianPengunjung.getText()+"%' OR nama_pengunjung LIKE '%"+textPencarianPengunjung.getText()+"%' ";
      new configDBOW().setJudulKolom(tabelPengunjung, Namanya);
      new configDBOW().cariData(tabelPengunjung, Namanya, SQLCari1);
      new configDBOW().setLebarJudulKolom(tabelPengunjung, LebarKolomPengunjung);
    }//GEN-LAST:event_textPencarianPengunjungKeyPressed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        try {
        if (textIDTransaksi.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"ID Transaksi belum diisi");
            textIDTransaksi.requestFocus();
        }else
        if(textNamaWisata1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Nama Wisata belum diisi");
            textNamaWisata1.requestFocus();
        }else
        if(textHargaTiket.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Harga Tiket belum diisi");
            textHargaTiket.requestFocus();
        }else
        if(textJumlahBeli.getText().isEmpty()){
           JOptionPane.showMessageDialog(null,"Jumlah Beli belum diisi");
            textJumlahBeli.requestFocus();
        }else
        if(textTotalBiaya.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Total Biaya belum diisi");
            textTotalBiaya.requestFocus();
        } else
        if (new configDBOW().getDuplikasiKey("transaksi","id_transaksi",textIDTransaksi.getText())==true){
            JOptionPane.showMessageDialog(null,"ID Transaksi sudah terdaftar");
            java.sql.Statement st = new configDBOW().getKoneksi.createStatement();
            java.sql.ResultSet rs = st.executeQuery("SELECT*FROM transaksi WHERE id_transaksi='"+textIDTransaksi.getText()+"'");
        if(rs.next()){
             textNamaWisata1.setText(rs.getString("id_pengunjung"));
             textHargaTiket.setText(rs.getString("id_wisata"));
             SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
             dateTransaksi.setDate(dt.parse(rs.getString("waktu_transaksi")));
             textJumlahBeli.setText(rs.getString("jumlah_beli"));
             textTotalBiaya.setText(rs.getString("total_biaya"));
}
}
         else{
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault());
            String TGL =sdf.format(dateTransaksi.getDate());
            String[] F = {"id_transaksi","nama_wisata","harga_tiket","waktu_transaksi","jumlah_beli","total_biaya"};
           String[] isinya ={textIDTransaksi.getText(),textNamaWisata1.getText(),textHargaTiket.getText(),TGL,textJumlahBeli.getText(),textTotalBiaya.getText()};
           new configDBOW().SimpanDinamis("transaksi", F, isinya);

            new configDBOW().setTampilTabel(tabelTransaksi,Transaksi, SQL2);
            new configDBOW().setLebarJudulKolom(tabelTransaksi, LebarKolomTransaksi);
            

          
}
        } catch (Exception e) {
            System.out.print(e.toString());
}
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        new configDBOW().tampilLaporan("src/laporan/LapTransaksi.jrxml","SELECT*FROM transaksi");
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
         try {
        if (
            (textIDTransaksi.getText().isEmpty()) &&(textNamaWisata1.getText().isEmpty())&&(textHargaTiket.getText().isEmpty())&& (dateTransaksi.getDate().equals(null)) && (textJumlahBeli.getText().isEmpty()) &&(textTotalBiaya.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null,"Silahkan pilih data sebelum proses hapus ");
            tabelTransaksi.requestFocus();
       } else{
           
            new configDBOW().HapusDinamis("transaksi", "id_transaksi", textIDTransaksi.getText());
            new configDBOW().setTampilTabel(tabelTransaksi,Transaksi, SQL2);
            new configDBOW().setLebarJudulKolom(tabelTransaksi, LebarKolomTransaksi);
            }
} catch (Exception e) {
System.out.print(e.toString());
}
        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        try{
            
        
         if (
            (textIDTransaksi.getText().isEmpty()) && (textNamaWisata1.getText().isEmpty()) && (textHargaTiket.getText().isEmpty()) && (dateTransaksi.getDate().equals(null)) && (textJumlahBeli.getText().isEmpty()) &&  (textTotalBiaya.getText().isEmpty())){ 
            JOptionPane.showMessageDialog(null,"Silahkan pilih data sebelum proses ubah");
            tabelTransaksi.requestFocus();
         } else{
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd",
            Locale.getDefault());
            String TGL =sdf.format(dateTransaksi.getDate());
            String[] F = {"id_transaksi","nama_wisata","harga_wisata","jumlah_beli","total_biaya"};
            String[] isinya ={textIDTransaksi.getText(),textIDPengunjung.getText(),TGL,textJumlahBeli.getText(),textBiaya.getText()};
            new configDBOW().UbahDinamis("transaksi", "id_transaksi", textIDTransaksi.getText(), F, isinya);
            new configDBOW().setTampilTabel(tabelTransaksi,Transaksi, SQL2);
            new configDBOW().setLebarJudulKolom(tabelTransaksi, LebarKolomTransaksi);
         }
        } catch (Exception e) {
        System.out.print(e.toString());
                
    }       
    }//GEN-LAST:event_jButton16ActionPerformed

    private void textNamaWisata1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNamaWisata1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNamaWisata1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameAplikasiObjekWisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameAplikasiObjekWisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameAplikasiObjekWisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameAplikasiObjekWisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameAplikasiObjekWisata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbJenisKelamin;
    private com.toedter.calendar.JDateChooser dateTransaksi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPanel1;
    private javax.swing.JPanel panelBeranda;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelPariswisata;
    private javax.swing.JPanel panelPengunjung;
    private javax.swing.JPanel panelTransaksi;
    private javax.swing.JTable tabelPariswisata;
    private javax.swing.JTable tabelPengunjung;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JTextField textAlamat;
    private javax.swing.JTextField textAlamat1;
    private javax.swing.JTextField textBiaya;
    private javax.swing.JTextField textHargaTiket;
    private javax.swing.JTextField textIDPengunjung;
    private javax.swing.JTextField textIDTransaksi;
    private javax.swing.JTextField textIDWisata;
    private javax.swing.JTextField textJumlahBeli;
    private javax.swing.JTextField textKategori;
    private javax.swing.JTextField textNamaLengkap;
    private javax.swing.JTextField textNamaWisata;
    private javax.swing.JTextField textNamaWisata1;
    private javax.swing.JTextField textPencarianPengunjung;
    private javax.swing.JTextField textPencarianTransaksi;
    private javax.swing.JTextField textPencarianWisata;
    private javax.swing.JTextField textStatus;
    private javax.swing.JTextField textStock;
    private javax.swing.JTextField textTelepon;
    private javax.swing.JTextField textTempatLahir;
    private javax.swing.JTextField textTotalBiaya;
    // End of variables declaration//GEN-END:variables
    }
